[package]
name = "mindy-engine"
version = "0.10.1"
edition = "2024"

[dependencies]
gloo-timers = "0.3.0"
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
serde_json = "1.0.140"
serde_yaml = "0.9.34+deprecated"

[lib]
name = "mindy_engine"
path = "src/lib.rs"
